### ISSUE TITLE
can't search for sirfetch'd

### ISSUE THREAD

**Issue by ghalib5000** [tactlessfish/pokesummary#13]
this is a really useful software to use, unfortunatly i can't search ofr sirfetch'd. i think that may be because of the name having ' in it. can you check this problem? thanks

**Comment by seasonedfish** [comment]
Thanks for reporting this issue! I'll look into it.

**Comment by seasonedfish** [comment]
I see the issue now. When I give "sirfetch'd" as string, the `.title()` function thinks the d is the start of a new word, so it converts it to "Sirfetch'D". When I remove `.title()` from the input processing, it works.
<img width="667" alt="Screen Shot 2021-11-07 at 9 28 41 PM" src="https://user-images.githubusercontent.com/29507110/140680028-a84c3844-bdd1-46b6-8790-ed5cfd188909.png">

However, I don't want to require the user to manually capitalize pokemon names. This [Stackoverflow question](https://stackoverflow.com/questions/8199966/python-title-with-apostrophes) has some possible solutions to our problem.

**Comment by seasonedfish** [comment]
Replaced `pokemon.rstrip().title()` with `string.capwords(pokemon)`, which seems to fix the issue.

**Comment by ghalib5000** [comment]
Thanks mate, you've done an amazing job with this app, really useful.

**Comment by seasonedfish** [comment]
No problem! Thank you for the kind words :)
